name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # ---- Python (Flask) ----
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---- Node / Playwright ----
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 18+ is fine

      - name: Install npm deps
        run: npm ci

      # Install browsers + system deps for Linux
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ---- Run Playwright (will auto-start Flask via webServer in config) ----
      - name: E2E tests
        env:
          FLASK_APP: app
          FLASK_ENV: development
          TEST_RESET: "1"
          TODO_DB: "todo-e2e.sqlite3"
        run: npx playwright test

      # Optional: upload HTML report
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
